### ISSUE TITLE
Optimizing Metadata Fetch Process

### ISSUE THREAD

**Issue by gounthar** [jenkinsci/plugin-modernizer-tool#207]
## Current Situation
When the only recipe applied is `io.jenkins.tools.pluginmodernizer.FetchMetadata`, the process includes compiling the plugins.

## Question
If the sole interest is to locally build and store the metadata for a set of plugins, is the plugin compilation step necessary?

## Potential Optimization
If the only goal is to fetch and store the plugin metadata, the plugin compilation step may be an unnecessary overhead.

## Proposed Approach
When the `FetchMetadata` recipe is the only one being applied, we should consider skipping the plugin compilation step.

## Benefits of this Optimization
1. **Faster Metadata Retrieval**: Eliminating the compilation step would make the metadata fetch process more efficient.
2. **Reduced Resource Utilization**: Users interested only in metadata would not need to expend resources on compiling the plugins.
3. **Simplified Workflow**: The metadata fetch process would become more straightforward and focused.

## Considerations
- Evaluate any potential dependencies or side effects that may arise from skipping the compilation step.
- Ensure that the metadata can be reliably fetched and stored without the compilation.

## Next Steps
1. Assess the feasibility and implications of this optimization.
2. Implement the change to skip compilation when only the `FetchMetadata` recipe is applied.
3. Thoroughly test the modified process to ensure metadata integrity and reliability.

Your feedback and suggestions on this approach would be greatly appreciated.

**Comment by gounthar** [comment]
It looks like the compilation phase is still happening:

```
java -jar plugin-modernizer-cli/target/jenkins-plugin-modernizer-999999-SNAPSHOT.jar --plugins git,git-client,jobcacher --recipes FetchMetadata
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:ActiveProcessorCount=1
Starting Plugin Modernizer 
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:ActiveProcessorCount=1
Forking plugin git locally from repo git-plugin... 
Repository already forked to personal account gounthar 
Syncing the forked repository gounthar/git-plugin 
Fetching plugin code locally git... 
Metadata is not yet computed for plugin git. Using minimum JDK available 
Build failed 
Compiling plugin git with JDK 8 ... Please be patient 
Build failed 
Plugin git failed to compile with JDK 8. Trying next one 
Compiling plugin git with JDK 11 ... Please be patient 
Done 
Plugin git compiled successfully with JDK 11 
Collecting metadata for plugin git... Please be patient 
Done 
Running recipes FetchMetadata for plugin git... Please be patient 
Done 
Verifying plugin git with JDK 21... Please be patient 
The authenticity of host 'github.com (140.82.116.3)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
The authenticity of host 'github.com (140.82.116.3)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
```

Did I miss something?
Thanks.

**Comment by jonesbusy** [comment]
I was testing with the FQDN (which is also accepted apparently. I don't remember)

```--recipes io.jenkins.tools.pluginmodernizer.FetchMetadata```

But I was able to reproduce by

```
--recipes FetchMetadata
```

I need to convert the short name to FQDN before checking the recipe name. PR incoming

**Comment by gounthar** [comment]
Thanks 👍

**Comment by jonesbusy** [comment]
I think that now we can even do better and use directly object

from 

```diff
    @Option(
            names = {"-r", "--recipes"},
            required = true,
            description = "List of Recipes to be applied.",
            split = ",",
+           converter =  RecipeConverter.class,
            parameterConsumer = CommaSeparatedParameterConsumer.class)
-   private List<String> recipes;
+   private List<Recipe> recipes;
```

Same for plugin

```diff
    @Option(
            names = {"-p", "--plugins"},
            description = "List of Plugins to Modernize.",
            split = ",",
+           converter =  PluginConverter.class,
            parameterConsumer = CommaSeparatedParameterConsumer.class)
-   private List<String> plugins;
+   private List<Plugin> plugins;
```

I will allow validation directly on the CLI and avoid confusing by using String

Didn't try but should be supported by PICO

**Comment by jonesbusy** [comment]
Should be fixed by https://github.com/jenkinsci/plugin-modernizer-tool/pull/211
