### ISSUE TITLE
Add new command line option - list recipes

### ISSUE THREAD

**Issue by sridamul** [jenkinsci/plugin-modernizer-tool#24]
### What feature do you want to see added?

Command line option to list the available recipes with one line description of what it does.

### Are you interested in contributing this feature?

Yes!

**Comment by sridamul** [comment]
Hey @jonesbusy @gounthar , I think right now we can display the list of recipes as shown in this [yaml file](https://github.com/jenkinsci/plugin-modernizer-tool/blob/main/plugin-modernizer-core/src/main/resources/recipe_data.yaml). wdyt?

**Comment by gounthar** [comment]
That would be nice.

**Comment by jonesbusy** [comment]
> Hey @jonesbusy @gounthar , I think right now we can display the list of recipes as shown in this [yaml file](https://github.com/jenkinsci/plugin-modernizer-tool/blob/main/plugin-modernizer-core/src/main/resources/recipe_data.yaml). wdyt?

I think it's more than enough for the moment, could be improved in the future to display it nicely on the console
