### ISSUE TITLE
Unable to modernize plugin if not found on Plugin Health Score

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/plugin-modernizer-tool#279]
### Jenkins and plugins versions report

PHS doesn't collect data for new plugin. Because if that we cannot run plugin modernizer on recent plugin.

Remove the check and allow returning a "null" score

### What Operating System are you using (both controller, and any agents involved in the problem)?

All

### Reproduction steps

```bash
java -jar plugin-modernizer-cli/target/jenkins-plugin-modernizer-999999-SNAPSHOT.jar --dry-run --debug --plugins oss-symbols-api  --recipes FetchMetadata --github-owner jonesbusy-automation
```

### Expected Results

It doesn't fail

### Actual Results

It fail

### Anything else?

No

### Are you interested in contributing a fix?

Yes

**Comment by gounthar** [comment]
By the way, it is updated now: https://plugin-health.jenkins.io/api/scores.
