### ISSUE TITLE
`${maven.multiModuleProjectDirectory}` is an internal property and must not be used in pom.xml

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/plugin-modernizer-tool#51]
### What feature do you want to see added?

Remove `${maven.multiModuleProjectDirectory}`

Additionally it doesn't work with 'mvnd' maven daemon

```
style execution: Unable to find configuration file at location: ${maven.multiModuleProjectDirectory}/.mvn/checkstyle.xml: Could not find resource '${maven.multiModuleProjectDirectory}/.mvn/checkstyle.xml'. -> [Help 1]
```

maven-checkstyle-plugin should most likely to be adapted on child module to override the `configLocation`

**Comment by sridamul** [comment]
> maven-checkstyle-plugin should most likely to be adapted on child module to override the configLocation

you mean to replicate the `.mvn` dir in child modules?

**Comment by jonesbusy** [comment]
Most likely the plugin configuration.

What is common can stay on the pluginManagement on the parent.

Then you can overide on child module what is changing. 

The checkstyle configuration should not be duplicated
