### ISSUE TITLE
How do we fetch SCM URL of plugin?

### ISSUE THREAD

**Issue by sridamul** [jenkinsci/plugin-modernizer-tool#74]
### What feature do you want to see added?

To clone the plugin locally, the plugin's SCM URL is fetched from Update-center, which requires the user to input the plugin name exactly as in the update-center.json. Another option is to pass the repository path from GH URL. eg: `jenkinsci/git-client-plugin`

Is it an easy-to-use approach? 🤔

Open to other alternative approaches.

**Comment by jonesbusy** [comment]
I would say keep it simple for now and use the plugin short name. We will not modernize plugin hosted on a different organisation

**Comment by gounthar** [comment]
Yes, that's a good idea to keep it simple.
