### ISSUE TITLE
Allow to pass plugin via a plugin.txt

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/plugin-modernizer-tool#77]
### What feature do you want to see added?

Allow to pass a list of plugin to modernize via plugins.txt (perhaps we can extract the plugin ID by stripping the version).

User/developer are familiar with the plugins.txt and would allow long list of plugin instead of passing all of them via the CLI

**Comment by gounthar** [comment]
So you would get the `plugins.txt` from a running Jenkins controller thanks to the `jenkins-plugin-cli` binary, or are you referring to another method to get this file?
Thanks.

**Comment by jonesbusy** [comment]
For example, or simply reuse and existing `plugins.txt`

For example as a plugin maintainer I maintain a container image were I install all my plugin using the https://github.com/jenkinsci/plugin-installation-manager-tool

My idea would be to reuse the same format so that both tool can consume the `plugins.txt`

**Comment by gounthar** [comment]
Thanks for the clarification.
That's also the method I use for https://github.com/jenkins-docs/quickstart-tutorials .

I was just wondering: would plugin maintainers use that method to create automatic PRs to plugins' repositories listed as dependencies for their own plugin? 🤔 
I would, for sure, you also would, Mark also maybe, but I'm not sure lots of developers would.
It would help me, though, so of course I'm all for it.
