### ISSUE TITLE
Ensure a repository is clean when plugin is already cloned

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/plugin-modernizer-tool#85]
### What feature do you want to see added?

When repository is already cloned, perform a git clean and pull. Also ensure it's on the main branch (fetch the main branch from github ?

**Comment by gounthar** [comment]
I think this may be linked:
![image](https://github.com/user-attachments/assets/6c9ca202-c847-4c53-92c4-f2e261223b00)
My repo was not up to date before this PR creation. 🤷

**Comment by jonesbusy** [comment]
Yep including this https://github.com/jenkinsci/plugin-modernizer-tool/issues/81

This require a small change upstream : https://github.com/hub4j/github-api/issues/1626

**Comment by jonesbusy** [comment]
Done here. Sure sure which PR tho

```java
LOG.debug("Resetting changes and pulling latest changes from {}", remoteUrl);
git.reset().setMode(ResetCommand.ResetType.HARD).call();
```
