### ISSUE TITLE
Ensure no PR creation when no changes applied

### ISSUE THREAD

**Issue by sridamul** [jenkinsci/plugin-modernizer-tool#91]
### Reproduction steps

Apply AddCodeOwner recipe to a plugin which already has code owners file

### Expected Results

There should be no PR creation, if the applied recipes don't change anything in the codebase

### Actual Results

There is a blank PR when no changes applied by the recipes
Eg: https://github.com/jenkinsci/build-timestamp-plugin/pull/65

### Are you interested in contributing a fix?

Yes

**Comment by sridamul** [comment]
Also, commits with no changes are added to the same PR if you execute the recipe multiple times.

**Comment by jonesbusy** [comment]
I think this is fixed. Please reopen if we still have any PR
