### ISSUE TITLE
Improving PR Title and Description Generation

### ISSUE THREAD

**Issue by gounthar** [jenkinsci/plugin-modernizer-tool#92]
### What feature do you want to see added?

The generic title "Automatic PR" is not sufficiently descriptive. We need to create a more meaningful title that accurately reflects the purpose of the pull request (PR).

## Recommendations:

1. **Generic Title**: Develop a default title that is both informative and broadly applicable to the modernization process.

2. **Customization Option**: If the generic title doesn't meet the user's needs, we should implement one of the following:
   - Add a command-line option to set a custom PR title
   - Create a variable that allows users to define their preferred title

3. **Recipe Descriptions**: When recipe descriptions are available, we should incorporate them into the PR body. This can be done as follows:
   - Create a separate section for each recipe
   - Use proper markdown formatting for improved readability
   - Example structure:

     ```markdown
     # Modernization Changes

     ## Recipe: [Recipe Name]
     [Recipe description]

     ## Recipe: [Another Recipe Name]
     [Another recipe description]

     ...
     ```

By implementing these changes, we can enhance the clarity and usefulness of our automatically generated PRs, making them more informative for reviewers and maintainers.

**Comment by jonesbusy** [comment]
I think this is quiet important for the adoption and the sake of release notes of plugins

![Screenshot from 2024-08-17 20-42-08](https://github.com/user-attachments/assets/f9b13156-9bc7-4e1f-8f07-e9be8e89a46f)

**Comment by jonesbusy** [comment]
Fixed by https://github.com/jenkinsci/plugin-modernizer-tool/pull/223
