### ISSUE TITLE
Add the description of the --plugin-file

### ISSUE THREAD

**Issue by gounthar** [jenkinsci/plugin-modernizer-tool#96]
### Describe your use-case which is not covered by existing documentation

In PR #86, we introduced a new feature that allows parsing an existing plugin file and applying recipes to the list of plugins contained within it. However, this functionality is not yet described in the current documentation.

Specifically, the documentation should cover:

1. How to use the new feature to parse an existing plugin file
2. The format requirements for the plugin file
3. How to apply recipes to the list of plugins extracted from the file
4. Any limitations or considerations when using this approach

This additional documentation would help users understand and utilize the new functionality effectively, especially those who manage multiple plugins and want to streamline the modernization process.

By updating the documentation to include this use-case, we can ensure that users are aware of all available options and can choose the most efficient method for their specific needs.

**Comment by sridamul** [comment]
Will update the docs after adding `--jenkins-uc` option

**Comment by berviantoleo** [comment]
Please add documentation for `--jenkins-uc` too.

**Comment by sridamul** [comment]
sure
